#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.0.{build}

# Do not build on tags
skip_tags: false

# Start builds on tags only
skip_non_tags: false

# Skipping commits affecting specific files
skip_commits:
  files:
  - '**\AssemblyInfo.*'
  - 'CHANGELOG.md'
  - 'README.md'

# 
pull_requests:
  do_not_increment_build_number: true
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:
- ps: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        $env:PoGoEmulator_Version = "$($env:APPVEYOR_REPO_TAG_NAME.Replace('v', ''))";
    }
    else
    {
        $env:PoGoEmulator_Version = "$($env:APPVEYOR_BUILD_VERSION)";
    }        



# clone directory
clone_folder: c:\projects\PoGoEmulator

# fetch repository as zip archive
shallow_clone: false

# set clone depth
# clone entire repository history if not defined
clone_depth:  5

# environment variables
environment:
CHANGELOG_GITHUB_TOKEN: 
  secure: QcKCFS7oLerve4UOpe314Y3jok6BAXbbAyorTwQqykQjJHaTDLzDhhphiZ+l6h1m
auth_token: 
  secure: QcKCFS7oLerve4UOpe314Y3jok6BAXbbAyorTwQqykQjJHaTDLzDhhphiZ+l6h1m
priv_key: 
  secure: uq+HbJgbeT/46/itva7G3WsqDrcFtO+c/Fpn6NSCphvd3uQM75j9z9BUme7oUgThopA+pFU7XT63mYqznFiVxNy7sLloMCGcaUChqwlIfng1fq/LOPk1jUWSMPbADg4jmIx3lk1jL3WZRMXER24IyrvjMjETEbXKZ0wle4+unU0wb3Zug8WxkGcvW0Nme6Q5MB8v2WbvkYLlgY5c5OMfwzQ67Qg1QIDC8oMQusW6aPyjgRY/CnpcOhqraScghPJHARXt63poxhxpj522Oj925N5bzvtBbLiIkCp41g4Rl47u1TJ1RlA9d8N4VaYuJWVBy+SWC/1L2cxuQvG+K3e81hmKlkx093+ZKz7UXA/dSfZG/8WqUCV7P8gMxb0YB6GsoqwSj+DvLu+UdiK8qLY5ZPmY5WdAcRUdM991Yp6A+aEVzF4Cs/+GeALGulIYtIFRPT8b0pWi7mV2o2xstchQqL17i6YHXi/BEKzr3ekYCIlRnDenvGEzh98pnLGfrrS0dkSRd1eukp7ZDSqeNr5Sx1/S0guAALjMoQoZIFkbjUEQBcGMie8Jef/vYrVpB8v31pNOexQ+FIJej4ecjcIiJkpKetLBRAgX/8TsUaOQE8fBAkWM27VyWZsXTg+lYRq/wbacNseRwtX1CHLrK7+fgNEkUk/HzUuDmzXyLN0SFIwwaE+1PC+KW6hyXLvzq6RBdk3G8LzVNoY75LNYuDEje7fsJHDkqUDczoaZ+3MrornZOaJQ+nS2hMmjZleNyYDi2Wq/3fRK35H0e3RJg0Rk3xKHC5b8zXsIkRaxpNPK4/kOs0vbTBjvNcZSKkO6j77g7AdfBBWNwqtuDaObI1AOwn/cvtxFNdtvndB+yyfZUaN6wKOzr/r02pU4IN7YFVKTP914wyKYFn5djq2FCtbfcbm4Y3qGjpAjAme/1KkW3F5nxrQ7/2qwhBsvR8n+RRhxFUZPMoVOM8mkkTsScu8U2DJ3Vhi2yFrG4/AqVtexdeTLK4rfRcgn/z8hNQPIC5eDl+fSmDsI2vOxRARg11uh2FAlcNEKcLEn1flXlB5gS9CaW0EurhhOrqm6OL0X+b+/WWabI05LlzdCYSF19sCszDuxIOYItRR9iQZEY/4soaC3i9S3i/CLl4ox1m/pZPISOeknf9EjsEGuGsUdf5cyjZgVdcnUTeUc65WU9tc+cc0ud25k5ytLz44qxnlvore98O/2ISjPmR13Wtx6cMIV7KHpSs+FwnYD+S6OiFK4eQoIvJ7p5GsUddztCpe9bhqAitKHi8L0Zbo6tI+TUOK4u27dLtoi25aS7UzGrmzyKViHwGPEaK+b5wtNV9qet7A0tu5BWulZ/A6SaSE0eTwO+9ir8Q/RwOGp1+4oeMbTBJprckPGeAzqCxLrVg50dxY4okzQ8MC2kcrJeWBxScAJ8lckW9/CPrPxLD+Gvh8XFaf4f144LCIxba9KIpS9teDYzK9UIabcIVBW5B42HsnOV8eutUgiKIk21B9UDg5LINMI5htJjDo3t55qsfVZ6jq7FwMTro4zz3nZ4UvL15jJHL9TsSCnr/LDYvwgNo1isT04JiGFMvuQUZ8t5G7oDQ0L5LEV0qjpn4wPakETaglN71Jg/guG7J7rl3E3gvFUZdN9JrchxYqqubZIYs2sydO6Ha/DfxN1pVkOq2lnWUfXRBbuCLIwMpr0A+o7+k7XV2QoVp8eOGTG3S6U0GK5AVSZtHHMZfYUzGMhnPhYsaCMyTFHWhzkHuKbF22y45RybCXACrRcQWBcybh+YUZtPiCEe1GkEufJ6n9ASxB+fCbsv6R5MJ0bgP7x+U1rIoXiN944Ssd9BWyW5eKqGhOWfxSi8mqOGRVPNP7C0FV0nWi6q6rUTwqNQVNTqJ/oO7ZvtNX0wVLyJB7x7KIOgY1C7qdZXdPxwe3/hgCTix42SsHFa4g02kd3pxbeOOzi0o1ZLT2LMmr5NCLIV0tIXiWU2YSkHuRnDdzWm7DK5YKYzOzaYhqJ4Ddh0caxC4qOD926MsLUgOXqVejdNWu+dSzr5MlbPjNl8NXWeWB7/wCe13KDFAdwVZUGjRtVD3AASnueXada8ilkfxVv7NDuYzvRRZDfz91JBaxAAApoJTjQDGOmvsPHvc6SveEnJy/lDkSyGKGa75Gw2M6l6YbPI7AGgsmInPosRBpo1FS8mSoF18bIKl0G/3lneeR5TJHs8tTlJ7ZURp7mjEvzqzfB+TkFP2M6b+WiQe5rS8VSe86dybdhfkS4oAMg7xRhXrVAj7Uhl74ILnXg5ANW0mzPUWWR95LUdPrVEpgx6WtbLBAM4hYLhXxqGSynpHw76lPpW0RTHXC5syqTAIM53lRTFcv3xj7oHaFFLI/O9eLxBhWOtdCI/UVFFMB+KCENYs+EAqtAcRPU2eh8h2s9sId5yJlokUpjZntpLb2FoDx/rmQuCODLXHhtjb83mqb9te+WJlg1RJtHngQkA0bBtx+Tfg4BOYMMyH3DGgQ5S3o/myAaN30pA9oNZnOtKNpH6nsOCfzE5v3uPIOa7Tbm4/JcnVv+9B8Hn9qCU6zKGVjJcIXI+lpnf09MGO6pqn6mLtwpkcP0MAGEscUH3vZIyNWS8hDuYuZ9EgeSDwaoBCoAwT6a5bQ7wQ/UqL6hSx+2UoJUE52uuPKQrxXM+zvMb77SocBig/MXGv1NvSvxzKxp6mDPny2axSUx9I83OEj/UHAYL+1mG2SoYo3KTooh5sXGmTaZgp8KvvSwW0u01i48JlIooePDb8G7gwHqoWM3F5e0FMT21sDLivMhnlx8gaZrHoNwNgNo/Z2xjoq233Tj6BdbjoXWtxvD2ocG1DZ92knXCzF17pIEJa06vRjdfL2Rj1Ugy29Q2JZGL/Pt2jToJfnXrtEJl71KaPIyT5y6amySOGtYt3i8h/wRdVUIIJHb3MAp0dsCakfAAy2dNAX0rC1+qBruNo37n+B/8TMTKRfkDYgcBAxhHOCGgjMS2No5nDmIvCIDBLQO6UWdqyQCxMlviPmgTO96yMSGWCE0go2CkGwnJRsNoDV8fnYpgxggGDICMBIjl7vg/6ExWaz4xxzcXn11DN64RDqdPLyC+ZZ3hZUOciHujAZOiyzATVoGc3Ry+nVlh2m8sz5bifgoGfXxVrd+jaieJBHEHnr0MD4H9g6sW8WkBVwLeKTcs0hppT85uTfilOSClP9xQwFYNVpMpsuev0Q098NqzbbeeBpicRPlMbpZ7UjWLbE2FGUpoDNkNcaCipmnZPaCSn5wtaDqmZwybJE17ceBOKyycXJTyGU2mOI3m7lWDvolM6QPomKRkoF1TOOVQTgQQwBS8o2DGUlZ3onkZlxQAPkezdz/sj0oXUBca1ZzbCGLAAILxdz8VMqqyk9ApplPmDwe9eM0cULPiv6c0l9aT5QFiEvbUsVocfHf4JRqRXk+o0xSZ4eUGRihxRPHyigvYAkYCbokqRqkV5gyK+q2SlLNW0jDS/oTglAB4l4AnHxvBRQSvvgxqjMUQRxXo3N2mue0iq9Bi9q/L2sMYfu9LYd/jYqktne7Dq/y/NKjj5iTawG0F00jHNA9Or1uHRSJ0oQAxb28BfKTdsN2lLbvbrQcNmAcM9JAaEsVMeCQcEdFKx9ykf2k/eicd2+npS+PGR3T6c66lU5+YR0oOMWLymg5nqVj4DxJdcX/CahmFeX2DnKF38YgcWD6z+JIUWn6VZYRD8nJ0PeLaBVw4QEdXDcEKkjHuQonLjPEOLujfecIIREwkpZFOzjEZFVdbC/EBgcJFzy07/HSIXRmU4VrupP9N7uhNEa9AioGgluLhuNT3IrK6CiNHkIxIdOT67x1aXRyvxKdDlCUIrcITPDgFbGdvdX6xUS3jBfgn2v1714kotHtVLc++C6Q6FzZM3a0xUYoL5G80szvgZRxs1LY1a/09WbpmDa6hHyoVxg4HjhgZPrhtZP6JrDB/x2tvlD71WGree784W0y/KjqfKLUPLW0KMAykGFxrmBY6hj78QdnnF4fFOiYk0Lf0RMuT6Ri/VQn8Cb1jAET1w==
github_email:
  secure: XZXS5+eJOubB91e0LtqIEinf84icR3+URjbX5YbWnc8=
github_user: 
  secure: K1enFpkh00HL+0rlpKbUfQ==
  
#  matrix:
#    - ruby_version: "21" # Older version, but matches Travis-CI
#    - ruby_version: "21-x64"

# build cache to preserve files/folders between builds
#cache:
#  - packages -> **\packages.config  # preserve packages directory in the root of build folder but will reset it if packages.config is modified
#  - '%LocalAppData%\NuGet\Cache'

# scripts that run after cloning repository
install:
- git submodule update --init --recursive

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: false
  file: '**\AssemblyInfo.*'
  assembly_version: '$(PoGoEmulator_Version)'
  assembly_file_version: "1.0.0.0"
  assembly_informational_version: '$(APPVEYOR_REPO_TAG_NAME)'

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
#platform: x86
platform: Any CPU

# to add several platforms to build matrix:
#platform:
#  - x86
#  - Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# to add several configurations to build matrix:
#configuration:
#  - Debug
#  - Release

build:
  # MSBuild verbosity level
  project: PoGoEmulator.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

# scripts to run before build
before_build:
  - nuget restore
  - dotnet restore

# scripts to run *after* solution is built and *before* automatic packaging occurs (web apps, NuGet packages, Azure Cloud Services)
before_package:

# scripts to run after build
after_build:
- ps: >-
    Remove-Item "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)" -Recurse -ErrorAction Ignore;
    New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)";
    New-Item -ItemType Directory -Force -Path "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)";
    if ($env:PLATFORM -eq "x86")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\PoGoEmulator\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\PoGoEmulator" -Force;
    }  
    elseif ($env:PLATFORM -eq "x64")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\PoGoEmulator\bin\$($env:PLATFORM)\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\PoGoEmulator" -Force;
    }
    elseif ($env:PLATFORM -eq "Any CPU")
    {
        Move-Item -Path "$($env:APPVEYOR_BUILD_FOLDER)\PoGoEmulator\bin\$($env:CONFIGURATION)" -Destination "$($env:APPVEYOR_BUILD_FOLDER)\$($env:PLATFORM)\$($env:CONFIGURATION)\PoGoEmulator" -Force;
    }
        

# to run your custom scripts instead of automatic MSBuild
build_script:

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to disable automatic tests
test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  - path: '\$(PLATFORM)\$(CONFIGURATION)\PoGoEmulator'
    name: PoGoEmulator
    

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# providers: Local, FTP, WebDeploy, AzureCS, AzureBlob, S3, NuGet, Environment
# provider names are case-sensitive!
deploy:

  # Deploy to GitHub Releases
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: '[CHANGELOG.md](https://github.com/msx752/PoGoEmulator/blob/master/CHANGELOG.md)'
    release: PoGoEmulator $(APPVEYOR_REPO_TAG_NAME)
    auth_token: $(auth_token)
    artifact: PoGoEmulator
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true

# scripts to run before deployment
before_deploy:
- ps: >-
    $fileContent = "-----BEGIN RSA PRIVATE KEY-----`n";
    $fileContent += $env:priv_key.Replace(' ', "`n");
    $fileContent += "`n-----END RSA PRIVATE KEY-----`n";
    Set-Content "$env:USERPROFILE\.ssh\id_rsa" "$($fileContent)";
    Set-Content "$env:USERPROFILE\.git-credentials" "https://$($env:auth_token):x-oauth-basic@github.com`n";

- git config --global credential.helper store
- git config --global user.email "%github_email%"
- git config --global user.name "%github_user%"
- git checkout -b Appveyor "%APPVEYOR_REPO_BRANCH%"
- SET PATH=C:\Ruby23-x64\bin;%PATH%

# Print version and location for pre-installed ruby
- ruby --version
- where ruby

# Install latest version of RubyGems
- gem update --system --no-document --no-post-install-message
- gem --version
- where gem

# Print version and location for pre-installed bundler
#- bundler --version
#- where bundler

# Install ruby dependencies
- gem install bundler
- bundle install
#- bundle install --retry 3
- bundle exec github_changelog_generator

- git add "CHANGELOG.md"
- git add "PoGoEmulator/Properties/AssemblyInfo.cs"
- git commit -m "%APPVEYOR_REPO_TAG_NAME%"
- git checkout "%APPVEYOR_REPO_BRANCH%"
- git merge Appveyor
- git branch -d Appveyor
- git pull "origin" "%APPVEYOR_REPO_BRANCH%"
- git push "origin" "%APPVEYOR_REPO_BRANCH%"

# scripts to run after deployment
after_deploy:

# to run your custom scripts instead of provider deployments
deploy_script:

# to disable deployment
#deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

# on successful build
on_success:

# on build failure
on_failure:

# after build failure or success
on_finish:
